"""Docker-gated reconstructed-source ingestion and decompiler gap tracking."""
from __future__ import annotations

import hashlib
from pathlib import Path

from .backlog import DecompilerGap, append_gap
from .ingest import IngestionResult, ingest_source
from .sandbox import run_isolated


def decompile_pyc(path: str | Path, *, backlog_path: str | Path,
                  image: str = "pycmp-bytecode-worker:latest", timeout_seconds: int = 30) -> IngestionResult | None:
    """Attempt decompilation without executing a bytecode artifact.

    A failure creates a deduplicated local ticket and returns ``None``; callers
    keep the separately generated bytecode graph as the usable view.
    """
    path = Path(path).resolve()
    completed = run_isolated(image=image, input_path=path,
                             command=["uncompyle6", f"/input/{path.name}"], timeout_seconds=timeout_seconds)
    if completed.returncode:
        raw = path.read_bytes()
        append_gap(backlog_path, DecompilerGap(raw[:4].hex(), "uncompyle6", "DecompilerFailure",
                                               hashlib.sha256(raw).hexdigest(), completed.stderr[-1000:]))
        return None
    return ingest_source(completed.stdout, origin=str(path), reconstructed=True)
